app/js/question_controller.js, app/js/sumo_db.js, app/js/utils.js
@Rik r? just opening for now, will clean up the commit bits once we reach this PR
=> Bug 1061548 add user metadata to question onpost

app/css/lists.css, app/js/templates.js, app/question_list_helper.html, app/views/question_list_day.html
This was really upsetting my OCD, so I just fixed it.
=> Fix typo in "buddyup-list"

app/home.html, app/index.html, app/js/kb_controller.js, app/js/settings.js, app/js/sumo_db.js, app/js/templates.js, app/kb.html, app/profile.html, app/question.html, app/question_list_helpee.html, app/question_list_helper.html, app/views/kb_item.html
Only the latest commit is new. The rest is from #63.
=> [Bug 1125883] Suggested articles 

app/js/question_controller.js
Probably best viewed with ?w=1
=> [Bug 1126728] Race: Remove the global user from question_controller.js

app/authentication.html, app/home.html, app/js/authentication_controller.js, app/js/sumo_db.js, app/js/user.js, app/js/utils.js
=> [bug 1121638] Implement login for SUMO accounts

app/authentication.html, app/js/password_reset_controller.js, app/js/sumo_db.js, app/password_reset.html
The last commit is the only one we care about. The others are from the login PR.
r?
=> [bug 1121641] Implement password reset

app/authentication.html, app/js/registration_controller.js, app/js/sumo_db.js, app/js/user.js, app/registration.html
The last commit is the only one we care about. The rest are from other PRs.
r?
=> [bug 1121639] SUMO account registration

app/css/buddyup.css, app/email_confirmation.html, app/js/email_confirmation_controller.js, app/js/helper_profile_controller.js, app/js/registration_controller.js, app/js/user.js, app/registration.html
=> [bug 1123766] Email confirmation screen

app/js/helper_profile_controller.js
=> Fix linting issue

app/js/notifications.js, app/js/question_controller.js, app/js/user.js, app/test/unit/mocks/mock_notifications.js, app/test/unit/mocks/mock_sumo_db.js, app/test/unit/notifications_test.js, app/test/unit/user_test.js, app/test/unit/utils_test.js
Only the last commit (023300fa2ec15eed943479926f46600c887613b8) is part of this bug. The others are from https://github.com/mozilla/buddyup/pull/83
=> [bug 1110860] Notification resolved 

app/js/question_controller.js, app/js/sumo_db.js, app/js/templates.js, app/views/thread_header.html
=> [bug 1061596] Categories

app/css/base.css, app/css/buddyup.css, app/css/question.css, app/js/question_controller.js, app/question.html
=> [bug 1109133] Auto resize the question input field

app/js/question_controller.js
=> [bug 1135634] Deactivate question taken by someone else

app/index.html
=> [bug 1136103] Prevent zooming on application

app/js/questions_controller.js
=> [bug 1143103] No Questions are showing under "My Questions"

app/email_confirmation.html, app/index.html, app/js/email_confirmation.js, app/js/email_confirmation_controller.js, app/js/registration_controller.js, app/js/user.js, app/registration.html
=> [bug 1135276] [bug 1137168] Email verification bugs

app/authentication.html, app/css/buddyup.css, app/css/buttons.css, app/css/icons.css, app/email_confirmation.html, app/helper_profile.html, app/home.html, app/js/libs/font_size_utils.js, app/kb.html, app/password_reset.html, app/profile.html, app/question.html, app/question_list_helpee.html, app/question_list_helper.html, app/registration.html
- Import font_size_utils.js from Gaia. It helps center headers.
- Change HTML of headers to work better with building blocks
- Remove most app code for headers
=> [bug 1137223] Header styles

app/css/buddyup.css, app/css/comment.css, app/css/icons.css, app/css/profile.css, app/js/profile_controller.js, app/js/templates.js, app/js/user.js, app/profile.html, app/question.html, app/views/my-profile.html, app/views/thread_header.html
- Removed unnecessary styles in buddyup.css
- Styled the options in the profile page
- Wording changes on profile page
- Changed the way we store the handset type
- Changed some <buttons> to <a> because of building blocks
- Includes a temporary fix for buttons on the question page
=> [bug 1137235] Button styling and profile options

app/css/buddyup.css, app/css/comment.css, app/css/question.css, app/js/question_controller.js, app/js/templates.js, app/question.html, app/views/comment.html, app/views/thread.html, app/views/thread_header.html
- Cleanup in buddyup.css
- Fix for bug 1137186
- Removed a bit of repetition with create_comment_wrapper. Not perfect but already better
=> [bug 1137190] Thread bubble design

app/authentication.html, app/css/authentication.css, app/css/base.css, app/css/buttons.css, app/css/email_confirmation.css, app/css/error-list.css, app/email_confirmation.html, app/password_reset.html, app/registration.html
=> [bug 1141019] [bug 1141020] [bug 1141022] User authentication pages

app/js/helper_profile_controller.js, app/js/notifications.js
Bug 1149584 - Top helpers profile is missing user name if the user has not set a display name
=> Bug 1146932 - "Null has commented on a question"

README.md, app/test/marionette/.jshintrc, app/test/marionette/home_test.js, app/test/marionette/lib/buddyup.js, app/test/marionette/lib/remote_calls.js, app/test/marionette/lib/views/home.js, app/test/marionette/lib/views/question.js, app/test/marionette/lib/views/view.js, package.json, scripts/run-integration-tests-server.sh, scripts/run-integration-tests.sh
First draft, still WIP.
How to run it:
```
npm install
cd gaia
TEST_FILES=./apps/buddyup/test/marionette/home_test.js make test-integration
```
=> Bug 1155589 - Add the first marionette test

app/js/profile_controller.js
=> [bug 1148427] Add more supported locales

app/js/sumo_db.js
=> [bug 1182880] Add locale filtering

.gitignore, app/authentication.html, app/helper_profile.html, app/home.html, app/js/templates.js, app/password_reset.html, app/profile.html, app/question.html, app/question_list_helpee.html, app/question_list_helper.html, app/registration.html, package.json, tasks/get_localization.js
This is pretty much #172 again, just against a better branch. To test
* `npm install`
* `grunt get_localization`
* `grunt`
* Configure your browser to use a different language (in Firefox: Preferences > Content > Languages)
* Open the app.
* Browse to a page that has strings. My usual test case is the profile page. Asking a question and editing questions also have translations.
r?
=> [Bug 1158912] Use translations from Sumo

README.md, tasks/get_localization.js
Talking with @mozillamarcia in `#buddyup`, I realized a couple issues with the localization. This fixes those.
r?
=> Easier l10n

app/authentication.html, app/helper_profile.html, app/home.html, app/js/l10n.js, app/js/load_translations.js, app/password_reset.html, app/profile.html, app/question.html, app/question_list_helpee.html, app/question_list_helper.html, app/registration.html
=> [Bug 1195792] Move loading translations out of an inline script, to make CSP happy.

app/js/settings.js
=> [Bug 1193972] Remove unwanted locales.

Gruntfile.js, tasks/extract.js
=> Update extract task to 1) get new templates 2) actually work.

Gruntfile.js, app/views/main/question.html, app/views/main/unsupported_locale.html
=> [Bug 1201151] Mark html strings in templates as safe.

app/index.html, app/test/unit/notifications_test.js
=> [Bug 1201865] Include l10n.js everywhere notifactions.js is included.

app/email_confirmation.html, app/unsupported_locale.html
=> [Bug 1202230] Fix loading of l10n.js in email_confirmation and unsupported_locale

app/index.html, app/js/l10n.js
=> [bug 1201865] Fix notifications

app/views/main/authentication.html, app/views/main/home.html, app/views/main/password_reset.html, app/views/main/registration.html, app/views/my-profile.html
=> [bug 1207230] Make missing strings localizable

app/js/sumo_db.js
=> [bug 1206870] Tag unsupported locale questions as english

app/js/utils.js
This isn't ideal, since it doesn't tie into the Firefox OS localization tools for this, but at least it is localized.
r?
=> [Bug 1204968] Make relative times localizable.

app/authentication.html, app/email_confirmation.html, app/helper_profile.html, app/home.html, app/index.html, app/js/sumo_db.js, app/js/user.js, app/js/utils.js, app/kb.html, app/password_reset.html, app/profile.html, app/question_list_helpee.html, app/question_list_helper.html, app/registration.html, app/unsupported_locale.html
=> [Bug 1209472] Set the locale of newly created accounts based on device locale
